# Note: startup_wait is a maximum, not an absolute value

default:
  startup_wait: 120
  jetty_port: 8983
  java_version: ">= 1.7"
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"
test:
  startup_wait: 120
  jetty_port: 9983
  java_version: ">= 1.7"
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"